### ISSUE TITLE
module go version

### ISSUE THREAD

**Issue by ldez** [Antonboom/nilnil#20]
It's possible for you to downgrade the version inside your go.mod to go1.20?

the new way to handle the module and go version is strict.

https://github.com/golangci/golangci-lint/actions/runs/5893637045/job/15985603630?pr=4023

https://go.dev/blog/toolchain

https://github.com/golangci/golangci-lint/pull/4023

**Comment by Antonboom** [comment]
@ldez Hi! Done.

It's my bad – these linters are simple and do not require 1.21 API.
But what about the new ones?

**Comment by ldez** [comment]
> But what about the new ones?

For now, I will just ask to downgrade but the new Go version management system is really viral.

The Go version inside the go.mod should be set to the real required version.
But as the community has to habit to update the Go version to the latest version every time a new Go version is happening, I think it will force everyone to use the latest version.

**Comment by Antonboom** [comment]
What are the rules for updating a `go.mod` in **golangci-lint**? If the new linter really requires modern Go (for example, `slices` and `maps`, which are gaining popularity now), then you will have to update the **golangci-lint** module
