### ISSUE TITLE
Detect the opposite situation?

### ISSUE THREAD

**Issue by Antonboom** [Antonboom/nilnil#4]
```go
return entity, errors.New("something went wrong")

// should be
return nil, errors.New("something went wrong")
```

**Comment by itimky** [comment]
That's a great idea!  
What do you think about a separate option for this detection to preserve backwards compatibility?

**Comment by Antonboom** [comment]
@itimky, hi!

Nice to see you 🙂 

I agree. If you have time, please contribute. Or I can do this if it is relevant to real life (at the time of creating the issue I was not sure that this was a real case).

But I am not sure about the best naming for new option. Maybe `--detect-reverse=true`  🤷

**Comment by itimky** [comment]
Glad to see again you too, pal 🤗

I tried to find some real life cases and did not find any 🤔

**Comment by itimky** [comment]
On a second thought, I saw constructions like this:

```go
func get(..) (*Entity, error) { .. }

func SomeFn() (*Entity, error) {
  ..
  
  return get(..)
}
```

Is such case relevant?
